alumno_index:
    path:     /
    defaults: { _controller: "AppBundle:Alumno:index" }
    methods:  GET

alumno_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Alumno:show" }
    methods:  GET

alumno_new:
    path:     /new
    defaults: { _controller: "AppBundle:Alumno:new" }
    methods:  [GET, POST]

alumno_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Alumno:edit" }
    methods:  [GET, POST]

alumno_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Alumno:delete" }
    methods:  DELETE
