profesor_index:
    path:     /
    defaults: { _controller: "AppBundle:Profesor:index" }
    methods:  GET

profesor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Profesor:show" }
    methods:  GET

profesor_new:
    path:     /new
    defaults: { _controller: "AppBundle:Profesor:new" }
    methods:  [GET, POST]

profesor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Profesor:edit" }
    methods:  [GET, POST]

profesor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Profesor:delete" }
    methods:  DELETE
