registro:
    path:     /registro/check
    defaults: { _controller: "AppBundle:Principal:registro" }
    methods:  [GET, POST]

login:
    path:     /registro/login
    defaults: { _controller: "AppBundle:Principal:login" }
    methods:  [GET, POST]