registro:
    path:     /registro/check
    defaults: { _controller: "AppBundle:Principal:registro" }
    methods:  [GET, POST]

login:
    path:     /principal
    defaults: { _controller: "AppBundle:Principal:login" }
    methods:  [GET, POST]

logout:
    path:     /
    defaults: { _controller: "AppBundle:Principal:logout" }
    methods:  [GET, POST]