app_principal:
    path:     /
    defaults: { _controller: "AppBundle:Principal:index" }
    methods:  [GET, POST]

app_alumno_back:
    resource: "@AppBundle/Resources/config/routing/back/alumnoBack.yml"
    prefix:   /Backend/alumno

app_profesor_back:
    resource: "@AppBundle/Resources/config/routing/back/profesorBack.yml"
    prefix:   /Backend/profesor

app_empresa_back:
    resource: "@AppBundle/Resources/config/routing/back/empresaBack.yml"
    prefix:   /Backend/empresa

app_registro_Y_login:
    resource: "@AppBundle/Resources/config/routing/registroYlogin.yml"
    prefix:   /

app_alumno_front:
    resource: "@AppBundle/Resources/config/routing/front/alumnoFront.yml"
    prefix:   /alumno

app_profesor_front:
    resource: "@AppBundle/Resources/config/routing/front/profesorFront.yml"
    prefix:   /profesor

app_empresa_front:
    resource: "@AppBundle/Resources/config/routing/front/empresaFront.yml"
    prefix:   /empresa

