app_principal:
    path:     /
    defaults: { _controller: "AppBundle:Principal:index" }
    methods:  [GET, POST]

app_alumno:
    resource: "@AppBundle/Resources/config/routing/alumno.yml"
    prefix:   /Backend/alumno

app_profesor:
    resource: "@AppBundle/Resources/config/routing/profesor.yml"
    prefix:   /Backend/profesor

app_empresa:
    resource: "@AppBundle/Resources/config/routing/empresa.yml"
    prefix:   /Backend/empresa

app_registro_Y_login:
    resource: "@AppBundle/Resources/config/routing/registroYlogin.yml"
    prefix:   /